# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mahyar Alizadeh
title: CRM analyst & Software Developer
email: me@mahyar.io
website: https://mahyar.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: 02syntaxerror
github_username:  ma-alizadeh
# facebook_username: jekyll
#instagram_username: mahyaralizadeh
linkedin_username: mahyaralizadeh

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Professional Summary
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Highly-skilled software development professional bringing more than 15 years in business analysis, software design and development.Sound knowledge of sales and marketing requirements of a global CRM system.Works well under pressure and consistently meets deadlines and targets while delivering high quality work.

content:
  - title: Skills # Title for the section    
    layout: text
    content: | # this will include new lines to allow paragraphs
       - C# & .Net Expert	
       - PHP 	& Laravel
       - Databases (MS SQL Server & mySql)
       - UML Data Modeling 
       - Process Engineering 
       - CRM (Deploy & Development)
       - LMS (Deploy & Development)
       - Basic 	knowledge of HTML5, CSS, Javascript and jQuery
       - Basic 	knowledge of Android Application
       - Unity Game Engine
       - Agile 	and SCRUM development	
       - Team Collaboration Tools(Git, TFS, Slack, Jira)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rai-Mana Institute of Coaching & Leadership
        link: https://rai-mana.com
        # link_text: boringcompany.com
        sub_title: CRM & LMS Administrator
        caption: Apr 2020 - Present 
        quote: >
          SuitesCRM, Moodle, Wordpress
        description: | # this will include new lines to allow paragraphs
           The main focus of this company is designing, localizing and implementing competent courses in leadership and coaching programs. Due to covid 19 pandemic situation, the company decided to make their courses online which  resulted in massive growth in sales. As Rai-Mana CTO I am responsible for CRM,CMS and LMS development and administration. My main focus is to find the best required platforms and components, deploy and maintain them and create custom features using freelance programmers. I'm also responsible for Evaluating and configuring our CRM platform, and providing detailed end user documentation.    
      - layout: left
        title: Hoorakhsh Studios
        link: https://hoorakhsh.studio
        # link_text: boringcompany.com
        sub_title: Lead Game Developer
        caption: November 2017 - Apr 2020
        quote: >
          Unity Engine, C#, PHP
        description: | # this will include new lines to allow paragraphs
           The main focus of this company was to create 2D animations & games. My job as lead programmer was to collaborate with Art & Game Design teams and turn their requests into features which can be developed by team. As a unity & c# programmer my main coding focus was to build required tools and structures for other developers & game designers. I also built required APIâ€™s for one of the projects using Laravel & PHP.
      - layout: left
        title: Vijegi Team
        #link: https://hoorakhsh.studio
        # link_text: boringcompany.com
        sub_title: Co-Founder & Head of Development
        caption: April 2015 - October 2017
        quote: >
          ASP.NET, MS SQL Server, Telerik Ajax, Telerik Reporting
        description: | # this will include new lines to allow paragraphs
           The main focus of this company was to build psychological assessment tools to help HR departments to optimize the entire spectrum of HR processes, from finding the right candidate to fill a position. The main challenge was establishing product specifications and processing client requirements. My job was to develop these online assessment tools in collaboration with 2 other software engineers.
           - Developed web-based platform for psychological assessment using ASP.net, Entity Framework and MS SQl Server.
           - Designed reports to present assessment results using Telerik Reporting Tool.
           - Implemented innovative systems for data collection using Telegram Bots API and PHP.
           - Worked closely with clients to establish product specifications and system designs.
           - Assessed costs and risks associated with developing new features and products.
      - layout: left
        title: Operation Research Group
        # link: https://hoorakhsh.studio
        # link_text: boringcompany.com
        sub_title: Developer & Project Manager
        caption: April 2012 - April 2015
        quote: >
          WCF, C#, SQl Server, DevExpress
        description: | # this will include new lines to allow paragraphs
           The main focus of this company was to build civil project monitoring and evaluation softwares.My job as project manager was to develop new features & mobile apps in my team and train and mentor junior programmers. I worked with 5 other programmers and we applied Agile Scrum Framework.
           - Developed shared central authentication system in c# for intranet applications.
           - Developed data change tracking system and reports using MS Sql Server CDC.
           - Worked closely with clients to establish product specifications and system designs.
           - Identified and suggested new technologies and tools for enhancing product value and increasing team productivity like GitLab,Slack,Trello and Jira.
           - Led a group of 4 engineers in the design, and development of c#-based software solutions.
           - Designed and built mobile application for on-site data collection using Java, Android Studio and Google Map API.
      - layout: left
        title: Safa Industrial Group
        link: https://www.safagroup.com
        # link_text: boringcompany.com
        sub_title: CRM Developer
        caption: 2010 - Aug 2013
        quote: >
          C#,MS Sql Server,EF
        description: | # this will include new lines to allow paragraphs
         Safa Industrial Group was a large holding consisting of more than 7 steel production plants and 14 related companies with over 3500 employees. 
         I worked as a developer/designer in the CRM team. My responsibilities was:
         - Create use-case scenarios in collaboration with the analysis team.
         - Develop, tests and deploy scalable, highly available and modular software products using C# & SOA.
         - Apply unit tests.
         - Perform UAT (User Acceptance Test)
      - layout: left
        title: Metosad Co
        # link: https://hoorakhsh.studio
        # link_text: boringcompany.com
        sub_title: Junior Developer
        caption: 2006 - 2010
        quote: >
          VB.net, C#, MS Sql Server, Crystal Reports
        description: | # this will include new lines to allow paragraphs
         The main focus of the company was to make a civil projects documentation software based on PMBOK standards.As a C# programmer I was responsible for maintaining,debugging and developing Windows Form Applications.
         - Maintained existing applications and implemented and delivered new applications.
         - Developed object-oriented softwares, including Civil Project Documentation Systems based on PMBOK standards.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Azad University Tehran West Branch
        caption: 2007 - 2009
        sub_title: Associate of Applied Science - Software Engineering     
  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
       - Persian: Native Speaker
       - English: Proficient
       - German: Conversant B1
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Camping in nature
      - Gaming
      - Cooking
      - Volunteering in Environmental NGOs     
  - title: Certificates
    layout: text center
    content: | # this will include new lines to allow paragraphs         
      ![alt text](images/profile.jpg "Trees")    

      ![alt text](images/profile.jpg "Trees")


footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
