# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mahyar Alizadeh
title: CRM analyst & Software Developer
email: me@mahyar.io
website: https://mahyar.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: 02syntaxerror
github_username:  ma-alizadeh
# facebook_username: jekyll
#instagram_username: mahyaralizadeh
linkedin_username: mahyaralizadeh

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Professional Summary
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Highly-skilled software development professional bringing more than 15 years in business analysis, software design and development.Sound knowledge of sales and marketing requirements of a global CRM system.Works well under pressure and consistently meets deadlines and targets while delivering high quality work.

content:
  - title: Skills # Title for the section    
    layout: text
    content: | # this will include new lines to allow paragraphs
       - C# & .Net Expert	
       - PHP 	& Laravel
       - Databases (MS SQL Server & mySql)
       - UML Data Modeling 
       - Process Engineering 
       - CRM (Deploy & Development)
       - LMS (Deploy & Development)
       - Basic 	knowledge of HTML5, CSS, Javascript and jQuery
       - Basic 	knowledge of Android Application
       - Unity Game Engine
       - Agile 	and SCRUM development	
       - Team Collaboration Tools(Git, TFS, Slack, Jira)

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rai-Mana Institute of Coaching & Leadership
        link: https://rai-mana.com
        # link_text: boringcompany.com
        sub_title: CRM & LMS Administrator
        caption: Apr 2020 - Present 
        quote: >
          SuitesCRM, Moodle, Wordpress
        description: | # this will include new lines to allow paragraphs
           The main focus of this company is designing, localizing and implementing competent courses in leadership and coaching programs. Due to covid 19 pandemic situation, the company decided to make their courses online which  resulted in massive growth in sales. As Rai-Mana CTO I am responsible for CRM,CMS and LMS development and administration. My main focus is to find the best required platforms and components, deploy and maintain them and create custom features using freelance programmers. I'm also responsible for Evaluating and configuring our CRM platform, and providing detailed end user documentation.
    content:
      - layout: left
        title: Hoorakhsh Studios
        link: https://hoorakhsh.studio
        # link_text: boringcompany.com
        sub_title: Lead Game Developer
        caption: November 2017 - Apr 2020
        quote: >
          Unity Engine, C#, PHP
        description: | # this will include new lines to allow paragraphs
           The main focus of this company was to create 2D animations & games. My job as lead programmer was to collaborate with Art & Game Design teams and turn their requests into features which can be developed by team. As a unity & c# programmer my main coding focus was to build required tools and structures for other developers & game designers. I also built required APIâ€™s for one of the projects using Laravel & PHP.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)      
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
